import blockContent from './blockContent'
// import category from './category'
// import post from './post'
// import author from './author'
import review from './review'
import faq from './faq'
import team from './team'
import doc from './doc'
import contact from './contact'
import tourCategory from './tour-category'
import tourBasic from './tour-basic'
import tourToDate from './tour-to-date'
import currency from './currency'
import country from './country'
import agencyUser from './agencyUser'

export const schemaTypes = [ agencyUser, country, currency, tourCategory, tourBasic, tourToDate, review, faq, team, doc, contact, blockContent]
